# Site settings
title: Apache Flink&reg; Training
description: > # this means to ignore newlines until "baseurl:"
  Training material for Apache Flinkâ„¢, including environment setup
  implementation of programs using the Flink APIs, and packaging,
  execution and monitoring of Flink programs.
baseurl: ""
images: "/assets/images"
css: "/assets/css"
js: "/assets/js"
docs: https://ci.apache.org/projects/flink/flink-docs-stable
ff: https://www.ververica.com/flink-forward/resources
exercises-version: 3.1.0
flink-version: 1.10.0

tests: https://github.com/ververica/flink-training-exercises/blob/master/src/test/java/com/ververica/flinktraining/exercises/datastream_java
javasolutions: https://github.com/ververica/flink-training-exercises/blob/master/src/main/java/com/ververica/flinktraining/solutions/datastream_java
scalasolutions: https://github.com/ververica/flink-training-exercises/blob/master/src/main/scala/com/ververica/flinktraining/solutions/datastream_scala
javaexercises: https://github.com/ververica/flink-training-exercises/blob/master/src/main/java/com/ververica/flinktraining/exercises/datastream_java
scalaexercises: https://github.com/ververica/flink-training-exercises/blob/master/src/main/scala/com/ververica/flinktraining/exercises/datastream_scala
javaexamples: https://github.com/ververica/flink-training-exercises/blob/master/src/main/java/com/ververica/flinktraining/examples
scalaexamples: https://github.com/ververica/flink-training-exercises/blob/master/src/main/scala/com/ververica/flinktraining/examples

scala_version: "2.12"

# Build settings
markdown: kramdown

# Used in some documents to initialize arrays. Don't delete.
array: []
