# Site settings
title: Apache Flink&reg; Training
description: > # this means to ignore newlines until "baseurl:"
  Training material for Apache Flinkâ„¢, including environment setup
  implementation of programs using the Flink APIs, and packaging,
  execution and monitoring of Flink programs.
baseurl: "/flink-training" # the subpath of your site, e.g. /blog/
url: "http://dataartisans.github.io" # the base hostname & protocol for your site

scala_version: "2.10"

# Build settings
markdown: kramdown
